name:                holomev
version:             0.1.0.0
github:              "acmades/holomev"
license:             BSD3
author:              "Ivan Vazhenin"
maintainer:          "acmades@ya.ru"
copyright:           "2021 Acmades"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/acmades/holomev#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Learn.Function.Func

executables:
  holomev-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - holomev

tests:
  holomev-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - holomev
    - hspec
